/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;
import org.apache.poi.ss.usermodel.*;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import controllers.QuanLyHoaDon;
import controllers.QuanLyNhanVien;
import controllers.QuanLyTaiKhoan;
import controllers.QuanLyVP;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.Timestamp;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.Ban;
import models.Bill;
import models.Nguoi;
import models.NhanVien;
import models.VatPham;

/**
 *
 * @author ACER
 */
public class HomeAdminFrame extends javax.swing.JFrame {

    /**
     * Creates new form HomeAdminFrame
     */
    public HomeAdminFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
//        for (String item : cbString) {
//            cbxSP.addItem(item);
//        }

        qlVatPham = new QuanLyVP();
        qlHoaDon = new QuanLyHoaDon();
        LoadTableMonAn();
        LoadTableNV();
        LoadDoanhSo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        tabPanel = new javax.swing.JTabbedPane();
        panelAddItem = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNameItem = new javax.swing.JTextField();
        btnDeleteItem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableMenu = new javax.swing.JTable();
        btnAddItem = new javax.swing.JButton();
        btnUpdateItem = new javax.swing.JButton();
        txtPrice = new javax.swing.JTextField();
        panelAddItem1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableNV = new javax.swing.JTable();
        btnAddNV = new javax.swing.JButton();
        btnDeleteNV = new javax.swing.JButton();
        btnUpdateNV = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableDS = new javax.swing.JTable();
        btnExportExcel = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnSwitchNV = new javax.swing.JButton();
        btnSwitchSP = new javax.swing.JButton();
        btnSwitchDS = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 204, 255));

        jLabel3.setText("Đơn Giá");

        jLabel4.setText("Tên Sản Phẩm");

        txtNameItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameItemActionPerformed(evt);
            }
        });

        btnDeleteItem.setText("Xóa Món");
        btnDeleteItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteItemActionPerformed(evt);
            }
        });

        tableMenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã Sản Phẩm", "Tên Sản Phẩm", "Đơn Giá"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableMenu);

        btnAddItem.setText("Thêm Món");
        btnAddItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddItemActionPerformed(evt);
            }
        });

        btnUpdateItem.setText("Sửa Món");
        btnUpdateItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateItemActionPerformed(evt);
            }
        });

        txtPrice.setActionCommand("<Not Set>");
        txtPrice.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPriceActionPerformed(evt);
            }
        });
        txtPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPriceKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout panelAddItemLayout = new javax.swing.GroupLayout(panelAddItem);
        panelAddItem.setLayout(panelAddItemLayout);
        panelAddItemLayout.setHorizontalGroup(
            panelAddItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAddItemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAddItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(panelAddItemLayout.createSequentialGroup()
                        .addComponent(btnAddItem, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addGroup(panelAddItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelAddItemLayout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNameItem, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelAddItemLayout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAddItemLayout.createSequentialGroup()
                                .addGap(0, 44, Short.MAX_VALUE)
                                .addComponent(btnUpdateItem, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(btnDeleteItem, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        panelAddItemLayout.setVerticalGroup(
            panelAddItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAddItemLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(panelAddItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(txtNameItem, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAddItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(panelAddItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddItem, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateItem, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteItem, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabPanel.addTab("Sản Phẩm", panelAddItem);

        tableNV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Nhân Viên", "Họ Tên", "Ngày Sinh", "Địa Chỉ", "Tài Khoản", "Mật Khẩu", "Quyền"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tableNV);
        if (tableNV.getColumnModel().getColumnCount() > 0) {
            tableNV.getColumnModel().getColumn(0).setResizable(false);
        }

        btnAddNV.setText("Thêm Mới Nhân Viên");
        btnAddNV.setToolTipText("");
        btnAddNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNVActionPerformed(evt);
            }
        });

        btnDeleteNV.setText("Xóa Nhân Viên");
        btnDeleteNV.setToolTipText("");
        btnDeleteNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteNVActionPerformed(evt);
            }
        });

        btnUpdateNV.setText("Sửa Thông Tin Nhân Viên");
        btnUpdateNV.setToolTipText("");
        btnUpdateNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateNVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAddItem1Layout = new javax.swing.GroupLayout(panelAddItem1);
        panelAddItem1.setLayout(panelAddItem1Layout);
        panelAddItem1Layout.setHorizontalGroup(
            panelAddItem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAddItem1Layout.createSequentialGroup()
                .addGroup(panelAddItem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAddItem1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE))
                    .addGroup(panelAddItem1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(btnAddNV)
                        .addGap(38, 38, 38)
                        .addComponent(btnUpdateNV)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDeleteNV, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelAddItem1Layout.setVerticalGroup(
            panelAddItem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAddItem1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAddItem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAddItem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAddNV, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnUpdateNV, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnDeleteNV, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabPanel.addTab("Nhân Viên", panelAddItem1);

        tableDS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID Hóa Đơn", "Số Bàn", "Check in", "Check out", "Tổng Tiền", "Tên NV Thanh Toán"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tableDS);

        btnExportExcel.setText("Xuất file excel");
        btnExportExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportExcelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnExportExcel))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnExportExcel)
                .addGap(21, 21, 21)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabPanel.addTab("Hóa Đơn", jPanel4);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(tabPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(tabPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabPanel.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnSwitchNV.setText("Nhân Viên");
        btnSwitchNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSwitchNVActionPerformed(evt);
            }
        });

        btnSwitchSP.setText("Sản Phẩm");
        btnSwitchSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSwitchSPActionPerformed(evt);
            }
        });

        btnSwitchDS.setText("Doanh Số");
        btnSwitchDS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSwitchDSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSwitchNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSwitchSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSwitchDS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(btnSwitchSP, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSwitchNV, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSwitchDS, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(389, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSwitchSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSwitchSPActionPerformed
        // TODO add your handling code here:
        tabPanel.setSelectedIndex(0);
    }//GEN-LAST:event_btnSwitchSPActionPerformed

    private void btnSwitchNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSwitchNVActionPerformed
        // TODO add your handling code here:
        tabPanel.setSelectedIndex(1);
    }//GEN-LAST:event_btnSwitchNVActionPerformed

    private void btnUpdateItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateItemActionPerformed
        // TODO add your handling code here:
        if (selectedVP == null) {
            return;
        }

        btnAddItem.setEnabled(true);
        qlVatPham.UpdateVatPham(selectedVP.getID(), txtNameItem.getText(), Integer.parseInt(txtPrice.getText()));
        txtNameItem.setText("");
        txtPrice.setText("");
        selectedVP = null;
        LoadTableMonAn();
    }//GEN-LAST:event_btnUpdateItemActionPerformed

    private void btnAddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddItemActionPerformed
        // TODO add your handling code here:

        String name = txtNameItem.getText();
        int price = Integer.parseInt(txtPrice.getText());

        qlVatPham.Insert(name, price);
        VatPham vp = qlVatPham.GetVatPhamByName(name);
        if (vp.getID() == -1) {
            return;
        }

        NhapMenu(vp);
        dtm.setDataVector(vNDungMenu, vTieuDeMenu);
        tableMenu.setModel(dtm);
    }//GEN-LAST:event_btnAddItemActionPerformed

    private void btnDeleteItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteItemActionPerformed
        // TODO add your handling code here:
        int selectedRow = tableMenu.getSelectedRow();
        if (selectedRow > -1) {
            ArrayList<VatPham> list = qlVatPham.GetMenu();
            VatPham vp = list.get(selectedRow);
            qlVatPham.Delete(vp.getID());
        }

        LoadTableMonAn();
    }//GEN-LAST:event_btnDeleteItemActionPerformed

    private void txtNameItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameItemActionPerformed

    private void btnUpdateNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateNVActionPerformed

    private void btnDeleteNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteNVActionPerformed
        // TODO add your handling code here:

        if (tableNV.getSelectedRow() > -1) {
            Nguoi ng = nvArr.get(tableNV.getSelectedRow());
            QuanLyTaiKhoan.Ins.DeleteTaiKhoan(ng.getID());
            LoadTableNV();
        }
    }//GEN-LAST:event_btnDeleteNVActionPerformed

    private void btnAddNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNVActionPerformed
        // TODO add your handling code here:
        ThongTinNhanVienFrame ttFrame = new ThongTinNhanVienFrame();
        ttFrame.setVisible(true);
        HomeAdminFrame homeAdmin = this;

        //setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); // Sử dụng DISPOSE_ON_CLOSE để đóng Form 2
        // Thêm sự kiện đóng Form 2
        ttFrame.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent windowEvent) {
                // Hiển thị lại Form 1 khi Form 2 bị đóng
                homeAdmin.setVisible(true);
                LoadTableNV();
            }
        });

        homeAdmin.setVisible(false);
    }//GEN-LAST:event_btnAddNVActionPerformed

    private void txtPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPriceActionPerformed

    private void txtPriceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPriceKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtPriceKeyTyped

    private void btnSwitchDSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSwitchDSActionPerformed
        // TODO add your handling code here:
        tabPanel.setSelectedIndex(2);
    }//GEN-LAST:event_btnSwitchDSActionPerformed
   public String timestampToDate(Timestamp timestamp) {
        Date date = new Date(timestamp.getTime());
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy-HH:mm"); 
        return sdf.format(date);
    }
    private void btnExportExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportExcelActionPerformed

        try (Workbook workbook = new XSSFWorkbook()) {
            Sheet sheet = workbook.createSheet("Orders");

            Row headerRow = sheet.createRow(0);
            headerRow.createCell(0).setCellValue("ID");
            headerRow.createCell(1).setCellValue("Số bàn");
            headerRow.createCell(2).setCellValue("Check in");
            headerRow.createCell(3).setCellValue("Check out");
            headerRow.createCell(4).setCellValue("Tổng tiền");
            headerRow.createCell(5).setCellValue("Nhân viên");

            ArrayList<Bill> billArr = qlHoaDon.GetAllHoaDon();
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");

            int i = 1;
            for (Bill bill : billArr) {
                Row dataRow = sheet.createRow(i);
                dataRow.createCell(0).setCellValue(bill.getId());
                dataRow.createCell(1).setCellValue(bill.getSoBan());
                dataRow.createCell(2).setCellValue(timestampToDate(bill.getCheckOut()));
                dataRow.createCell(3).setCellValue(timestampToDate(bill.getCheckOut()));
                dataRow.createCell(4).setCellValue(bill.getTongTien());
                dataRow.createCell(5).setCellValue(bill.getHotenNV());
                System.out.println(bill.getCheckIn());

                i++;
            }

            try (FileOutputStream fileOut = new FileOutputStream("orders.xlsx")) {
                workbook.write(fileOut);
            }

            JOptionPane.showMessageDialog(null, "Data exported to orders.xlsx", "Success", JOptionPane.INFORMATION_MESSAGE);

        } catch (IOException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error exporting data", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnExportExcelActionPerformed

    /**
     * @param args the command line arguments
     */
    Vector vTieuDeMenu = new Vector();
    Vector vNDungMenu = new Vector();
    Vector vDongMenu;

    Vector vTieuDeDS = new Vector();
    Vector vNDungDS = new Vector();
    Vector vDongDS;

    Vector vTieuDeNV = new Vector();
    Vector vNDungNV = new Vector();
    Vector vDongNV;

    DefaultTableModel dtm = new DefaultTableModel();

    void TieuDeMenu() {
        vTieuDeMenu = new Vector();
        vTieuDeMenu.add("Mã Sản Phẩm");
        vTieuDeMenu.add("Tên Sản Phẩm");
        vTieuDeMenu.add("Đơn Giá");
    }

    void TieuDeNV() {
        vTieuDeNV = new Vector();
        vTieuDeNV.add("Mã Nhân Viên");
        vTieuDeNV.add("Họ Tên");
        vTieuDeNV.add("Ngày Sinh");
        vTieuDeNV.add("Địa Chỉ");
        vTieuDeNV.add("Tài Khoản");
        vTieuDeNV.add("Mật Khẩu");
        vTieuDeNV.add("Quyền");
    }

    void TieuDeDS() {
        vTieuDeDS = new Vector();
        vTieuDeDS.add("ID Hóa Đơn");
        vTieuDeDS.add("Số Bàn");
        vTieuDeDS.add("Check In");
        vTieuDeDS.add("Check Out");
        vTieuDeDS.add("Tổng Tiền");
        vTieuDeDS.add("Tên NV Thanh Toán");

    }

    void NhapMenu(VatPham sp) {
        vDongMenu = new Vector();
        vDongMenu.add(sp.getID());
        vDongMenu.add(sp.getTenVatPham());
        vDongMenu.add(sp.getGiaThanh());
        vNDungMenu.add(vDongMenu);
    }

    void NhapNV(Nguoi nguoi) {
        vDongNV = new Vector();
        vDongNV.add(nguoi.getID());
        vDongNV.add(nguoi.getHoVaTen());
        vDongNV.add(nguoi.getNgaySinh());
        vDongNV.add(nguoi.getDiaChi());
        vDongNV.add(nguoi.getTaiKhoan());
        vDongNV.add(nguoi.getMatKhau());

        String nameRole = QuanLyTaiKhoan.Ins.GetNameRole(nguoi.getIdQuyen());
        vDongNV.add(nameRole);

        vNDungNV.add(vDongNV);
    }

    void NhapDS(Bill bill) {
        vDongDS = new Vector();
        vDongDS.add(bill.getId());
        vDongDS.add(bill.getSoBan());
        vDongDS.add(bill.getCheckIn());
        vDongDS.add(bill.getCheckOut());
        vDongDS.add(bill.getTongTien());
        vDongDS.add(bill.getHotenNV());
        vNDungDS.add(vDongDS);
    }

    QuanLyVP qlVatPham;
    QuanLyHoaDon qlHoaDon;

    DefaultTableModel dtmMenu = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return column != 0 && column != 1 && column != 2;
        }
    };

    DefaultTableModel dtmDS = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return column != 0 && column != 1 && column != 2 && column != 3 && column != 4 && column != 5;
        }
    };

    DefaultTableModel dtmNV = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return column != 0 && column != 1 && column != 2 && column != 3 && column != 4 && column != 5 && column != 6;
        }
    };

    private void LoadTableMonAn() {
        TieuDeMenu();
        LoadMenu(qlVatPham.GetMenu());
    }

    private void LoadTableNV() {
        TieuDeNV();
        QuanLyNhanVien qlNhanVien = new QuanLyNhanVien();
        qlNhanVien.getNhanVien();
        LoadNV(qlNhanVien.GetAllData());
    }

    private void LoadMenu(ArrayList<VatPham> vatPhamArr) {
        TieuDeMenu();
        vNDungMenu = new Vector();
        for (VatPham vp : vatPhamArr) {
            NhapMenu(vp);
        }

        dtmMenu.setDataVector(vNDungMenu, vTieuDeMenu);
        tableMenu.setModel(dtmMenu);

        tableMenu.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 2) {
                    int selectedRow = tableMenu.getSelectedRow();
                    // Xử lý sự kiện double click ở đây, ví dụ:
                    selectedVP = vatPhamArr.get(selectedRow);
                    txtNameItem.setText(selectedVP.getTenVatPham());
                    txtPrice.setText(selectedVP.getGiaThanh() + "");
                    btnAddItem.setEnabled(false);
                }
            }
        });
    }

    private VatPham selectedVP;
    ArrayList<NhanVien> nvArr;

    private void LoadNV(ArrayList<NhanVien> nvArr) {
        this.nvArr = nvArr;
        vNDungNV = new Vector();
        for (NhanVien nv : nvArr) {
            NhapNV(nv);
        }

        dtmNV.setDataVector(vNDungNV, vTieuDeNV);
        tableNV.setModel(dtmNV);

    }

    private void LoadDoanhSo() {
        ArrayList<Bill> billArr = qlHoaDon.GetAllHoaDon();
        TieuDeDS();

        for (Bill bill : billArr) {
            NhapDS(bill);
        }

        dtmDS.setDataVector(vNDungDS, vTieuDeDS);
        tableDS.setModel(dtmDS);
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeAdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeAdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeAdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeAdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeAdminFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddItem;
    private javax.swing.JButton btnAddNV;
    private javax.swing.JButton btnDeleteItem;
    private javax.swing.JButton btnDeleteNV;
    private javax.swing.JButton btnExportExcel;
    private javax.swing.JButton btnSwitchDS;
    private javax.swing.JButton btnSwitchNV;
    private javax.swing.JButton btnSwitchSP;
    private javax.swing.JButton btnUpdateItem;
    private javax.swing.JButton btnUpdateNV;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel panelAddItem;
    private javax.swing.JPanel panelAddItem1;
    private javax.swing.JTabbedPane tabPanel;
    private javax.swing.JTable tableDS;
    private javax.swing.JTable tableMenu;
    private javax.swing.JTable tableNV;
    private javax.swing.JTextField txtNameItem;
    private javax.swing.JTextField txtPrice;
    // End of variables declaration//GEN-END:variables

    private double Date(long time) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
